baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "sfszh's blog"
[params]
Subtitle = "Subtitle"
GithubID = "sfszh"
TwitterID = "sfszh"
#AnalyticsID = "Your Google Analytics tracking code"
#DisqusShortname = "disqus_pWTBv4HJ7v"
Summary = true  # takes true or false
Content = false  # takes true or false
# if both are set to true, summary is shown.
# FooterMsg = "Copyright Me 2016. Powered by Hugo."
