baseurl = "http://sfszh.org/"
languageCode = "en-us"
title = "sfszh's little blog"
[params]
Subtitle = "keep it simple"
GithubID = "sfszh"
TwitterID = "sfszh"
#AnalyticsID = "Your Google Analytics tracking code"

DisqusShortname = "sfszh"
Summary = true  # takes true or false
Content = false  # takes true or false

# if both are set to true, summary is shown.
# FooterMsg = "Copyright Me 2016. Powered by Hugo."
